@hostname = localhost
@port = 7000
@host = {{hostname}}:{{port}}
@contentType = application/json

#POST https://{{host}}/authors/create
#Content-Type:{{contentType}}
#
#{
#    "name": "Joe",
#    "permissions": "author"
#}
#
###

# Comments
GET https://{{host}}/weatherforecast/

###

POST https://{{host}}/extra/1993?age=29
Accept :{{contentType}}
Content-Type : {{contentType}}

{
	"sumName":"Balmy"
}

###

POST https://{{host}}/wfc/
Content-Type:{{contentType}}

{
	"id":15,
	"sumName":"Balmy"
}
###

#GET https://www.bing.com